### ISSUE TITLE
Auto refresh too quick for long download lists

### ISSUE THREAD

**Issue by sethrd** [myfreeweb/transmitter#1]
I have about 30 torrents going. I'm unable to scroll more than 25% of the way through the list before the auto refresh happens, and takes me right back up to the top of the list. To over come this, I think a scroll should reset the refresh timer. I think that should be easy to do with JS.

Love the extension otherwise.

**Comment by valpackett** [comment]
Thanks for using Transmitter!

Haven't even tried long lists, honestly. Does it also reset the scroll position after you stop scrolling, if you stop scrolling before a refresh happens? I probably should save/restore the scroll position to prevent that. Actually I should use [data binding](https://simulacra.js.org) so that the elements get updated, not recreated from scratch every time. I wanted to have "no dependencies" but oh well :D

**Comment by sethrd** [comment]
When I scroll down, it will stop where I scrolled to for a split second, then jump back up to the top. It might not even be caused by the auto refresh.

**Comment by valpackett** [comment]
So it turns out, just reusing existing elements didn't help… any text modification results in a reflow and scroll jump in an extension popup. Solved by using a scrollable container instead of scrolling the whole window :) I'll publish a release soon.

**Comment by valpackett** [comment]
The new version has been already approved by addons.mozilla.org!
