### ISSUE TITLE
Change behavior for links to match Firefox UX

### ISSUE THREAD

**Issue by markus0m** [myfreeweb/transmitter#14]
The plugin should follow the standard procedure for download links and toolbar entries:
- Opening torrent links should either not open the Transmission page at all or at least open it in a new tab (ideally selectable through settings) - current page should stay open.
- Opening Transmission from the toolbar should open it in the current tab (like for other toolbar buttons like Home and Settings)

**Comment by valpackett** [comment]
> Opening Transmission from the toolbar should open it in the current tab (like for other toolbar buttons like Home and Settings)

It's just a regular link. It opens in the current tab if the current tab is empty. Just like opening Firefox settings. And just like them, it opens in a new tab otherwise. Which makes sense. Would be terrible to lose the current opened page!

Only Home always opens in the current tab, because that's its purpose.

> Opening torrent links should either not open the Transmission page at all or at least open it in a new tab (ideally selectable through settings) - current page should stay open.

Middle/ctrl click the magnet link to get it in the new tab if the link is not `target=_blank`.

I cannot influence this behavior, other than asking for page modification permissions and adding `target=_blank` to the links. I do not want these permissions. I strongly prefer addons that do NOT modify opened web pages.

The way torrent link handling works is that the link is opened *like a normal page*. My addon intercepts the *HTTP request*, does its thing and **redirects** to the Transmission page, which is the only reasonable thing it can do.

**Comment by markus0m** [comment]
Thanks for the explanation

>  It opens in the current tab if the current tab is empty.

Doesn't do that for me - it always opes another tab.

**Comment by valpackett** [comment]
Huh. Opens another tab for me now too. Opened in the empty tab earlier today. Whatever :D
