### ISSUE TITLE
Feature request - add torrent to category

### ISSUE THREAD

**Issue by kocane** [myfreeweb/transmitter#15]
When I download movies/tvshows I need to categorize them by adding them to a subfolder of the 'complete' downloads directroy, .e.g /movie/ or /tv/. Can you add a functionaility to allow adding torrents directly into these folders?

**Comment by valpackett** [comment]
Yeah that would be useful to me as well, I currently go into the web UI and click Set Location for this. I guess I could make a popup asking for the directory or something…

**Comment by kocane** [comment]
Good to hear. The Chrome addon I used before going back to Firefox, just added a submenu in the context menu entry where you could specify where you would add the torrent.  That'd be the most seamless way to do it anyway, with no input other than a rightclick needed.

Your work is much appreciated :-)

**Comment by clemux** [comment]
As a new user of this addon, I would be very happy too if that feature were to get implemented.

**Comment by abelk2** [comment]
Hi there.
I implemented this feature yesterday, because I needed it, and have just found this issue.
I've submitted it in a pull request, see above. Please review it.

This feature is especially useful when Transmission is used together with Plex Media Server, as plex gets confused when series and movies are in the same directory.
